name: CI

on:
  push:
    branches: 
     - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.3'
    - name: Hugo blog CI
      run: |
        hugo -D
        find ./public -name ".git" -type d -delete
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./public
      # env:
      #   PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #   PUBLISH_BRANCH: pages
      #   PUBLISH_DIR: ./public
